In [4]:
import numpy as np
from numpy import random
from scipy import stats
from enum import Enum

def nefia_level(lv):
  # _create_nefia関数
  # 10/15 は[1, LV+5]で一様分布
  # 4/15 で[1, 50] 
  # 1/15 で[1, 50] * 3 

  case = random.randint(15)
  if case in range(0, 9):
    return random.randint(lv + 5) + 1
  elif case in range(9, 14):
    return (random.randint(50) + 1)
  elif case == 14:
    return (random.randint(50) + 1) * 3
  else:
    raise Exception
def nefia_level_list(lv, amount):
  return np.array([nefia_level(lv) for i in range(amount)])

def stat_print(np_list):
  print("最大値: "+str(np_list.max()) + "\t最小値: "+str(np_list.min()))
  print("平均値: "+str(np_list.mean()) + "\t中央値: "+str(np.median(np_list)))
  print(np.percentile(np_list, [25, 50, 75]))

if __name__ == '__main__':
  lv_list_1 = nefia_level_list(1, 10000)
  stat_print(lv_list_1)

  lv_list_5 = nefia_level_list(5, 10000)
  stat_print(lv_list_5)

  lv_list_10 = nefia_level_list(10, 10000)
  stat_print(lv_list_10)

  lv_list_25 = nefia_level_list(25, 10000)
  stat_print(lv_list_25)
  
  lv_list_50 = nefia_level_list(50, 10000)
  stat_print(lv_list_50)

最大値: 150	最小値: 1
平均値: 15.8644	中央値: 5.0
[ 3.  5. 22.]
最大値: 150	最小値: 1
平均値: 16.9433	中央値: 8.0
[ 4.  8. 22.]
最大値: 150	最小値: 1
平均値: 18.1596	中央値: 11.0
[ 6. 11. 21.]
最大値: 150	最小値: 1
平均値: 22.987	中央値: 19.0
[10. 19. 28.]
最大値: 150	最小値: 1
平均値: 30.228	中央値: 28.0
[15. 28. 42.]
